name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run VPS

        run: curl -sSf https://sshx.io/get | sh -s run
    
